services:
  psql:
    build:
      context: ./
      dockerfile: ./docker/psql/Dockerfile
    container_name: libkeeper-psql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwe
      - POSTGRES_DB=libkeeper
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ./
      dockerfile: ./docker/api/Dockerfile
    container_name: libkeeper-api
    ports:
      - 8000:8000
    environment:
      - POSTGRES_HOST_ADDRESS=libkeeper-psql
      - POSTGRES_HOST_PORT=5432
      - SERVER_PORT=8000
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwe
      - POSTGRES_DB=libkeeper
      - SSL_MODE=disable
    depends_on:
      psql:
        condition: service_healthy
    command: bash -c "./api"

  app:
    build:
      context: ./
      dockerfile: ./docker/app/Dockerfile
    container_name: libkeeper-app
    ports:
      - 9000:9000
    environment:
      - APP_HOST=libkeeper-app
      - APP_PORT=9000
      - API_HOST=libkeeper-api
      - API_PORT=8000
    command: bash -c "node main.js"
