# Generated by Django 4.0.4 on 2022-05-22 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1000, verbose_name='Text')),
                ('date', models.IntegerField(verbose_name='Creation date')),
                ('checksum', models.CharField(max_length=64, verbose_name='Checksum')),
                ('note_id', models.IntegerField(verbose_name='Note ID')),
            ],
            options={
                'verbose_name': 'Version',
                'verbose_name_plural': 'Versions',
            },
        ),
    ]
